services:
  angela-core:
    image: angela-core:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        COMPUTE_BACKEND: gpu
    container_name: angela_core
    restart: unless-stopped
    ports:
      - "8091:8091"  # angela Core API
    volumes:
      - ./models:/app/models
      - ./config:/app/config
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - angela_PORT=8091
      - angela_MODELS_DIR=/app/models
      - angela_CONFIG_DIR=/app/config
      - angela_LOGS_DIR=/app/logs
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8091/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - angela_network

networks:
  angela_network:
    driver: bridge
