version: '3.8'

services:
  claraverse:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8069:8069"
    volumes:
      - clara-verse:/app
    networks:
      - traefik_default
networks:
  traefik_default:
    external: true
volumes:
  clara-verse:
